# Generated by Django 3.2.5 on 2021-07-21 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='flash_notes',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='created',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='flash_title',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='update',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.CharField(default=datetime.datetime(2021, 7, 21, 10, 35, 16, 761606, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashCard', to='flashcardApp.deck'),
        ),
    ]
