# Generated by Django 3.2.5 on 2021-07-21 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_image', models.ImageField(upload_to='images/')),
                ('flash_title', models.CharField(max_length=60)),
                ('flash_notes', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcardApp.subject')),
            ],
        ),
    ]
