# Generated by Django 3.2.5 on 2021-07-21 20:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcardApp', '0002_auto_20210721_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='answer',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='question',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='deck',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 20, 42, 15, 203468, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='deck',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='flashcardApp.category'),
        ),
    ]
