# Generated by Django 3.2.5 on 2021-07-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0003_auto_20210721_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='user',
        ),
    ]
