# Generated by Django 3.2.5 on 2021-07-21 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0003_remove_flashcard_flash_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
