# Generated by Django 3.2.5 on 2021-07-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0004_auto_20210721_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='flash_notes',
            field=models.CharField(max_length=255),
        ),
    ]
