# Generated by Django 3.2.5 on 2021-07-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0004_remove_flashcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='category',
        ),
    ]
